export type NovelStatus="DRAFT"|"PLANNING"|"GENERATING"|"PAUSED"|"COMPLETED"|"ARCHIVED";
export type ChapterStatus="PLANNED"|"GENERATING"|"GENERATED"|"VALIDATING"|"REVISION_REQUIRED"|"REVIEW"|"APPROVED"|"FINALIZING"|"CANONICAL";
